# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = 'https://han-wei-shen.github.io'
# Language used
languageCode = "en-us"
# Website title
title = "Han-Wei Shen"
# Theme used
theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10
[pagination]
    pagerSize = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# Configure main navbar links. They can have a weight to select the order.
# This links to content within the content /post/ folder
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 10

# This links to the page about.md
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 0

# Make the tags and categories pages accessible directly from the navbar.
[[menu.main]]
    name = "Research"
    url = "https://sites.google.com/view/gravity-research-group/research"
    weight = 5

[[menu.main]]
    name = "Publications"
    url = "https://sites.google.com/view/gravity-research-group/publications"
    weight = 20

[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 30

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """The homepage of Astatine. This website is a demo the of the \
    Hugo theme Astatine."""
    # Author of the site
    authorName = "Han-Wei Shen"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/hwshen_1.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = false

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
